### ISSUE TITLE
A humble request

### ISSUE THREAD

**Issue by paradoxmr24** [rahoolsingh/iamSinghRahul.github.io#4]
Sir, I have submitted a pull request on this repository of yours but it says as illegible on hactoberfest website please label my pull request as hacktoberfest-accepted, I will be very thankful to you

**Comment by rahoolsingh** [comment]
I labeled it with hacktoberfest-accepted, hope your problem is resolved now.

**Comment by paradoxmr24** [comment]
Thank you so much let me know whenever you need any help
